version: '2'
services:
  servicio1:
    image: docker.io/bitnami/mariadb:10.3
    container_name: contenedor1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=sebas
      - MARIADB_DATABASE=despliegue
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  servicio2:
    image: docker.io/bitnami/joomla:3
    container_name: contenedor2
    ports:
      - '80:4545'
      - '443:2020'
    environment:
      - JOOMLA_DATABASE_HOST=mariadb
      - JOOMLA_DATABASE_PORT_NUMBER=3306
      - JOOMLA_DATABASE_USER=sebas
      - JOOMLA_DATABASE_NAME=despliegue
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'joomla_data:/bitnami/joomla'
      - '/home/saludo/:/bitnami/joomla/html/'
    depends_on:
      - servicio1
volumes:
  mariadb_data:
    driver: local
  joomla_data:
    driver: local
